"""
Lilya settings for multiple project.

Generated by 'lilya createproject' using Lilya 0.24.3.
"""

from __future__ import annotations

from ..settings import AppSettings


class DevelopmentAppSettings(AppSettings):
    debug: bool = True
    app_name: str = "My application in development mode."
    title: str = "My multiple"
    environment: str | None = "development"
