services:
  db:
    restart: always
    image: postgres:16
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "lilya"
    expose:
      - "5432"
    command: >-
        --jit=false
    ports:
      - "127.0.0.1:5432:5432"

  redis:
    restart: always
    image: redis:latest
    expose:
      - 6379
    ports:
      - "6379:6379"
