services:
  db:
    restart: always
    image: docker.io/postgres:18
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "lilya"
    command: >-
        --jit=false
    ports:
        # if you don't specify e.g. localhost, it is by default exposed to the world
        # given the bad pws we shouldn't do that
      - "127.0.0.1:5432:5432"

  redis:
    restart: always
    image: docker.io/redis:latest
    ports:
      # if you don't specify e.g. localhost, it is by default exposed to the world
      # given the bad pws we shouldn't do that
      - "127.0.0.1:6379:6379"
