"""
Lilya settings for another project.

Generated by 'lilya createproject' using Lilya 0.24.3.
"""

from __future__ import annotations

from lilya.conf.global_settings import Settings


class AppSettings(Settings):
    app_name: str = "My application in production mode."
    title: str = "My another"
    environment: str | None = "production"
    secret_key: str = "lilya-insecure-bw6czu*j@67!a01j35eyt8+)5wxztw)1!(pbua_g2icqiy=@3f"
